In [ ]:
import os
os.chdir('/het/p4/ramirez/gcewavelets/skysearch/code/')

In [27]:
import numpy as np

In [28]:
arr_a = np.arange(3)
arr_b = 10 * np.arange(3)
arr_c = 100 * np.arange(3)
arr_d = 1000 * np.arange(3)

In [25]:
mesh_a, mesh_b, mesh_c = np.meshgrid(arr_a,arr_b,arr_c)
mesh = np.stack((mesh_c, mesh_a, mesh_b), axis=-1)
arr = mesh.reshape(3*3*3,3)

In [26]:
arr

array([[  0,   0,   0],
       [100,   0,   0],
       [200,   0,   0],
       [  0,   1,   0],
       [100,   1,   0],
       [200,   1,   0],
       [  0,   2,   0],
       [100,   2,   0],
       [200,   2,   0],
       [  0,   0,  10],
       [100,   0,  10],
       [200,   0,  10],
       [  0,   1,  10],
       [100,   1,  10],
       [200,   1,  10],
       [  0,   2,  10],
       [100,   2,  10],
       [200,   2,  10],
       [  0,   0,  20],
       [100,   0,  20],
       [200,   0,  20],
       [  0,   1,  20],
       [100,   1,  20],
       [200,   1,  20],
       [  0,   2,  20],
       [100,   2,  20],
       [200,   2,  20]])

In [31]:
mesh_a, mesh_b, mesh_c, mesh_d = np.meshgrid(arr_a,arr_b,arr_c,arr_d)
mesh = np.stack((mesh_d, mesh_c, mesh_a, mesh_b), axis=-1)
arr = mesh.reshape(3*3*3*3,4)

In [32]:
arr

array([[   0,    0,    0,    0],
       [1000,    0,    0,    0],
       [2000,    0,    0,    0],
       [   0,  100,    0,    0],
       [1000,  100,    0,    0],
       [2000,  100,    0,    0],
       [   0,  200,    0,    0],
       [1000,  200,    0,    0],
       [2000,  200,    0,    0],
       [   0,    0,    1,    0],
       [1000,    0,    1,    0],
       [2000,    0,    1,    0],
       [   0,  100,    1,    0],
       [1000,  100,    1,    0],
       [2000,  100,    1,    0],
       [   0,  200,    1,    0],
       [1000,  200,    1,    0],
       [2000,  200,    1,    0],
       [   0,    0,    2,    0],
       [1000,    0,    2,    0],
       [2000,    0,    2,    0],
       [   0,  100,    2,    0],
       [1000,  100,    2,    0],
       [2000,  100,    2,    0],
       [   0,  200,    2,    0],
       [1000,  200,    2,    0],
       [2000,  200,    2,    0],
       [   0,    0,    0,   10],
       [1000,    0,    0,   10],
       [2000,    0,    0,   10],
       [  

In [33]:
np.arange(1)

array([0])

In [34]:
mesh_a, mesh_b = np.meshgrid(arr_a,arr_b)
mesh = np.stack((mesh_a, mesh_b), axis=-1)
arr = mesh.reshape(3*3,2)

In [35]:
print(arr)

[[ 0  0]
 [ 1  0]
 [ 2  0]
 [ 0 10]
 [ 1 10]
 [ 2 10]
 [ 0 20]
 [ 1 20]
 [ 2 20]]
